service: bias-ui-web

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs22.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 512
  timeout: 30
  environment:
    NODE_ENV: ${self:provider.stage}

plugins:
  - serverless-single-page-app-plugin
  - serverless-offline

custom:
  singlePageAppPlugin:
    indexPath: dist/index.html
    notFoundPath: dist/index.html
    stripQueryString: true
    stripTrailingSlash: true

functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /{proxy+}
          method: get
    environment:
      NODE_ENV: ${self:provider.stage}

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}-${self:provider.region}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

    S3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref S3Bucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: s3:GetObject
              Resource: !Sub "${S3Bucket}/*"

package:
  patterns:
    - "!node_modules/**"
    - "!src/**"
    - "!*.ts"
    - "!*.tsx"
    - "!vite.config.ts"
    - "!tsconfig*.json"
    - "!package.json"
    - "!package-lock.json"
    - "!pnpm-lock.yaml"
    - "!.git/**"
    - "!.gitignore"
    - "!README.md"
    - "!dist/**"
    - "handler.js"
